            "Role: You are a senior security analyst specializing in vulnerability patching patterns. \n"
            "\n"
            "Task: Analyze multiple Git commits associated with a CVE and predict their relationships according to typical patterns.\n"
            "\n"
            "Input Data:\n"
            "- CVE ID and description\n"
            "- All commits in the patch group (Commit IDs and Messages, Branch/Versions information, Code diffs)\n"
            "\n"
            "Requirements: For each commit\n"
            "     a. Determine if it indeed fixes the CVE directly.\n"
            "     b. Identify key components/files modified.\n"
            "     c. Note any implicit signals available in commit messages and branch/version information (e.g., refinement-oriented wording or version-specific context).\n"
